### ISSUE TITLE
practica Architech

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practica-architect-bg55-a#1]
[Reporte de practica de Architec.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-bg55-a/files/7150482/Reporte.de.practica.de.Architec.pdf)

**Comment by Abraham890** [comment]
calificación: 18/20 puntos

**Comment by josealfredo79** [comment]
Faltan los parametros en los métodos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
